package main

import (
	"embed"
	"fmt"
	"math"
	"strconv"
	"strings"
)

//go:embed runtime/burrt.h runtime/burrt_natives.h
var runtimeFS embed.FS

// runtimeSources returns the embedded C runtime headers keyed by file name,
// to be written next to the generated program before invoking the C compiler.
func runtimeSources() map[string]string {
	out := map[string]string{}
	for _, name := range []string{"burrt.h", "burrt_natives.h"} {
		data, err := runtimeFS.ReadFile("runtime/" + name)
		if err != nil {
			panic("internal error: missing embedded runtime " + name)
		}
		out[name] = string(data)
	}
	return out
}

// cgen translates a compiled program (an entry function plus everything
// reachable through its constant pool) into a single C translation unit.
type cgen struct {
	shared *Shared
	b      strings.Builder
	ids    map[Obj]int // object -> stable id, assigned in registration order
	objs   []Obj       // objects in id order
	err    error
}

// genProgram emits the C source for fn, or returns an error for a construct
// the sequential backend does not yet handle (concurrency opcodes).
func genProgram(fn *OFunc, shared *Shared) (string, error) {
	g := &cgen{shared: shared, ids: map[Obj]int{}}
	// pin the built-in enums first so bur_*_enum are always available even
	// when a program never names Option/Result/Output in its constants
	g.register(shared.enums["Option"].runtime)
	g.register(shared.enums["Result"].runtime)
	g.register(shared.enums["Output"].runtime)
	entry := g.register(fn)

	g.b.WriteString("// Generated by the Burryn C backend. Do not edit.\n")
	g.b.WriteString("#include \"burrt.h\"\n\n")

	g.emitForwardDecls()
	g.emitObjectStorage()
	g.emitFunctionBodies()
	if g.err != nil {
		return "", g.err
	}
	g.emitInit()
	g.emitMain(entry)
	return g.b.String(), nil
}

// register assigns o (and everything it references) a stable id.
func (g *cgen) register(o Obj) int {
	if id, ok := g.ids[o]; ok {
		return id
	}
	id := len(g.objs)
	g.ids[o] = id
	g.objs = append(g.objs, o)
	switch t := o.(type) {
	case *OFunc:
		for _, c := range t.Chunk.Consts {
			if c.T == VObj {
				g.register(c.O)
			}
		}
	case *OVariantCtor:
		g.register(t.Enum)
	case *OEnumInst:
		g.register(t.Enum)
		for _, f := range t.Fields {
			if f.T == VObj {
				g.register(f.O)
			}
		}
	}
	return id
}

func (g *cgen) funcs() []*OFunc {
	var fns []*OFunc
	for _, o := range g.objs {
		if fn, ok := o.(*OFunc); ok {
			fns = append(fns, fn)
		}
	}
	return fns
}

func (g *cgen) emitForwardDecls() {
	for _, fn := range g.funcs() {
		fmt.Fprintf(&g.b, "static void bur_fn_%d(void);\n", g.ids[fn])
	}
	g.b.WriteString("\n")
}

// emitObjectStorage declares the object table and each function's constant
// array; both are populated by bur_init_objs.
func (g *cgen) emitObjectStorage() {
	fmt.Fprintf(&g.b, "static Obj *bur_K[%d];\n", len(g.objs))
	for _, fn := range g.funcs() {
		if len(fn.Chunk.Consts) > 0 {
			fmt.Fprintf(&g.b, "static Value bur_consts_%d[%d];\n", g.ids[fn], len(fn.Chunk.Consts))
		}
	}
	g.b.WriteString("\n")
}

// emitInit allocates every constant object (phase A) then wires up their
// cross-references and each function's constant array (phase B).
func (g *cgen) emitInit() {
	g.b.WriteString("static void bur_init_objs(void) {\n")
	// phase A: allocate shells
	for id, o := range g.objs {
		var typ, ctype string
		switch o.(type) {
		case *OString:
			typ, ctype = "OBJ_STRING", "OString"
		case *OFunc:
			typ, ctype = "OBJ_FUNC", "OFunc"
		case *OEnumType:
			typ, ctype = "OBJ_ENUMTYPE", "OEnumType"
		case *OVariantCtor:
			typ, ctype = "OBJ_VARIANTCTOR", "OVariantCtor"
		case *OEnumInst:
			typ, ctype = "OBJ_ENUMINST", "OEnumInst"
		default:
			g.fail(fmt.Errorf("unserializable constant object %T", o))
			return
		}
		fmt.Fprintf(&g.b, "\tbur_K[%d] = bur_alloc(sizeof(%s), %s);\n", id, ctype, typ)
	}
	for id := range g.objs {
		fmt.Fprintf(&g.b, "\tbur_add_root(bur_K[%d]);\n", id)
	}
	// phase B: populate fields
	for id, o := range g.objs {
		switch t := o.(type) {
		case *OString:
			fmt.Fprintf(&g.b, "\t{ OString *s = (OString *)bur_K[%d]; s->len = %d; s->data = (char *)malloc(%d); memcpy(s->data, %s, %d); s->data[%d] = 0; }\n",
				id, len(t.S), len(t.S)+1, cBytes(t.S), len(t.S), len(t.S))
		case *OEnumType:
			g.emitEnumType(id, t)
		case *OVariantCtor:
			fmt.Fprintf(&g.b, "\t{ OVariantCtor *c = (OVariantCtor *)bur_K[%d]; c->enm = (OEnumType *)bur_K[%d]; c->idx = %d; }\n",
				id, g.ids[t.Enum], t.Idx)
		case *OEnumInst:
			g.emitEnumInst(id, t)
		case *OFunc:
			g.emitFuncObj(id, t)
		}
	}
	// expose the built-in enums to the natives that construct them
	fmt.Fprintf(&g.b, "\tbur_opt_enum = (OEnumType *)bur_K[%d];\n", g.ids[g.shared.enums["Option"].runtime])
	fmt.Fprintf(&g.b, "\tbur_res_enum = (OEnumType *)bur_K[%d];\n", g.ids[g.shared.enums["Result"].runtime])
	fmt.Fprintf(&g.b, "\tbur_out_enum = (OEnumType *)bur_K[%d];\n", g.ids[g.shared.enums["Output"].runtime])
	g.b.WriteString("}\n\n")
}

func (g *cgen) emitEnumType(id int, t *OEnumType) {
	fmt.Fprintf(&g.b, "\t{ static VariantInfo vs[%d] = {", len(t.Variants))
	for i, v := range t.Variants {
		if i > 0 {
			g.b.WriteString(", ")
		}
		fmt.Fprintf(&g.b, "{%s, %d}", cStr(v.Name), v.Arity)
	}
	fmt.Fprintf(&g.b, "}; OEnumType *e = (OEnumType *)bur_K[%d]; e->name = %s; e->variants = vs; e->nvariants = %d; }\n",
		id, cStr(t.Name), len(t.Variants))
}

func (g *cgen) emitEnumInst(id int, t *OEnumInst) {
	fmt.Fprintf(&g.b, "\t{ OEnumInst *in = (OEnumInst *)bur_K[%d]; in->enm = (OEnumType *)bur_K[%d]; in->variant = %d; in->nfields = %d;",
		id, g.ids[t.Enum], t.Variant, len(t.Fields))
	if len(t.Fields) > 0 {
		fmt.Fprintf(&g.b, " in->fields = (Value *)malloc(sizeof(Value) * %d);", len(t.Fields))
		for i, f := range t.Fields {
			fmt.Fprintf(&g.b, " in->fields[%d] = %s;", i, g.cValue(f))
		}
	}
	g.b.WriteString(" }\n")
}

func (g *cgen) emitFuncObj(id int, fn *OFunc) {
	consts := "NULL"
	if len(fn.Chunk.Consts) > 0 {
		consts = fmt.Sprintf("bur_consts_%d", id)
	}
	file := "NULL"
	if fn.File != "" {
		file = cStr(fn.File)
	}
	fmt.Fprintf(&g.b, "\t{ OFunc *fn = (OFunc *)bur_K[%d]; fn->name = %s; fn->file = %s; fn->arity = %d; fn->numUpvals = %d; fn->code = bur_fn_%d; fn->consts = %s; fn->nconsts = %d;",
		id, cStr(fn.Name), file, fn.Arity, fn.NumUpvals, id, consts, len(fn.Chunk.Consts))
	for i, c := range fn.Chunk.Consts {
		fmt.Fprintf(&g.b, " bur_consts_%d[%d] = %s;", id, i, g.cValue(c))
	}
	g.b.WriteString(" }\n")
}

// cValue renders a constant Value as a C expression. Object values refer to
// their pinned slot in bur_K.
func (g *cgen) cValue(v Value) string {
	switch v.T {
	case VUnit:
		return "bur_unit()"
	case VBool:
		return fmt.Sprintf("bur_bool(%v)", v.B)
	case VInt:
		return fmt.Sprintf("bur_int((int64_t)UINT64_C(%d))", uint64(v.I))
	case VFloat:
		return fmt.Sprintf("bur_float(%s)", cFloat(v.F))
	case VObj:
		return fmt.Sprintf("bur_obj(bur_K[%d])", g.ids[v.O])
	}
	return "bur_unit()"
}

func (g *cgen) emitMain(entry int) {
	fmt.Fprintf(&g.b, `int main(int argc, char **argv) {
	bur_boot(argc, argv);
	bur_init_objs();
	bur_register_natives();
	bur_gc_ready = true;
	OClosure *entry = bur_new_closure((OFunc *)bur_K[%d]);
	bur_push(bur_obj((Obj *)entry));
	bur_cur_closure = entry;
	((OFunc *)bur_K[%d])->code();
	fflush(stdout);
	return 0;
}
`, entry, entry)
}

func (g *cgen) fail(err error) {
	if g.err == nil {
		g.err = err
	}
}

// ---- function body translation ----------------------------------------

func (g *cgen) emitFunctionBodies() {
	for _, fn := range g.funcs() {
		g.emitBody(fn)
		if g.err != nil {
			return
		}
	}
}

func (g *cgen) emitBody(fn *OFunc) {
	id := g.ids[fn]
	code := fn.Chunk.Code
	labels := g.jumpTargets(fn)

	fmt.Fprintf(&g.b, "static void bur_fn_%d(void) { // %s\n", id, fn.Name)
	fmt.Fprintf(&g.b, "\tint base = bur_cur->top - %d - 1; (void)base;\n", fn.Arity)
	g.b.WriteString("\tOClosure *self = bur_cur_closure; (void)self;\n")

	ip := 0
	for ip < len(code) {
		if labels[ip] {
			fmt.Fprintf(&g.b, "L%d:;\n", ip)
		}
		next := g.emitInst(id, code, ip)
		if g.err != nil {
			return
		}
		ip = next
	}
	if labels[len(code)] {
		fmt.Fprintf(&g.b, "L%d:;\n", len(code))
	}
	g.b.WriteString("}\n\n")
}

// jumpTargets scans a function's code once and returns the set of instruction
// offsets that are branch destinations, so a C label can be planted at each.
func (g *cgen) jumpTargets(fn *OFunc) map[int]bool {
	code := fn.Chunk.Code
	targets := map[int]bool{}
	ip := 0
	for ip < len(code) {
		op := code[ip]
		switch op {
		case OpJump, OpJumpIfFalse, OpJumpIfTrue, OpJumpIfFalsePop:
			targets[ip+3+int(readU16(code, ip+1))] = true
			ip += 3
		case OpLoop:
			targets[ip+3-int(readU16(code, ip+1))] = true
			ip += 3
		default:
			ip += instLen(op, code, ip, fn)
		}
	}
	return targets
}

// instLen returns the total byte length of the instruction at ip (opcode plus
// operands). OpClosure is variable-length: its upvalue descriptors depend on
// the referenced function's upvalue count.
func instLen(op byte, code []byte, ip int, fn *OFunc) int {
	switch op {
	case OpConst, OpGetLocal, OpSetLocal, OpGetGlobal, OpDefGlobal, OpSetGlobal,
		OpGetUpval, OpSetUpval, OpJump, OpJumpIfFalse, OpJumpIfTrue,
		OpJumpIfFalsePop, OpLoop, OpList:
		return 3
	case OpPopN, OpCall, OpSpawn, OpEndBlock, OpTestVariant, OpGetField:
		return 2
	case OpClosure:
		target := fn.Chunk.Consts[readU16(code, ip+1)].O.(*OFunc)
		return 3 + target.NumUpvals*3
	default:
		return 1
	}
}

func (g *cgen) emitInst(id int, code []byte, ip int) int {
	op := code[ip]
	w := func(format string, args ...any) { fmt.Fprintf(&g.b, "\t"+format+"\n", args...) }
	u16 := func(off int) int { return int(readU16(code, ip+1+off)) }

	switch op {
	case OpConst:
		w("bur_push(bur_consts_%d[%d]);", id, u16(0))
		return ip + 3
	case OpUnit:
		w("bur_push(bur_unit());")
		return ip + 1
	case OpTrue:
		w("bur_push(bur_bool(true));")
		return ip + 1
	case OpFalse:
		w("bur_push(bur_bool(false));")
		return ip + 1
	case OpPop:
		w("bur_pop();")
		return ip + 1
	case OpPopN:
		w("bur_cur->top -= %d;", code[ip+1])
		return ip + 2
	case OpCloseUpvalue:
		w("bur_close_upvalues(bur_cur->top - 1); bur_pop();")
		return ip + 1
	case OpEndBlock:
		w("{ Value v = bur_pop(); bur_close_upvalues(bur_cur->top - %d); bur_cur->top -= %d; bur_push(v); }", code[ip+1], code[ip+1])
		return ip + 2
	case OpGetLocal:
		w("bur_push(bur_cur->stack[base + %d]);", u16(0))
		return ip + 3
	case OpSetLocal:
		w("bur_cur->stack[base + %d] = bur_peek(0);", u16(0))
		return ip + 3
	case OpGetGlobal:
		n := g.constStr(id, u16(0))
		w("bur_push(bur_get_global(%s, %d));", cStr(n), len(n))
		return ip + 3
	case OpDefGlobal:
		n := g.constStr(id, u16(0))
		w("{ Value v = bur_pop(); bur_globals_put(%s, %d, v); }", cStr(n), len(n))
		return ip + 3
	case OpSetGlobal:
		n := g.constStr(id, u16(0))
		w("bur_set_global(%s, %d, bur_peek(0));", cStr(n), len(n))
		return ip + 3
	case OpGetUpval:
		w("bur_push(upvalue_get(self->upvals[%d]));", u16(0))
		return ip + 3
	case OpSetUpval:
		w("upvalue_set(self->upvals[%d], bur_peek(0));", u16(0))
		return ip + 3
	case OpEq:
		w("{ Value r = bur_bool(bur_eq(bur_peek(1), bur_peek(0))); bur_cur->top -= 2; bur_push(r); }")
		return ip + 1
	case OpNeq:
		w("{ Value r = bur_bool(!bur_eq(bur_peek(1), bur_peek(0))); bur_cur->top -= 2; bur_push(r); }")
		return ip + 1
	case OpGt, OpGtEq, OpLt, OpLtEq:
		kind := map[byte]int{OpGt: 0, OpGtEq: 1, OpLt: 2, OpLtEq: 3}[op]
		w("{ Value r = bur_compare(bur_peek(1), bur_peek(0), %d); bur_cur->top -= 2; bur_push(r); }", kind)
		return ip + 1
	case OpAdd:
		w("{ Value r = bur_add(bur_peek(1), bur_peek(0)); bur_cur->top -= 2; bur_push(r); }")
		return ip + 1
	case OpSub, OpMul, OpDiv, OpMod:
		ch := map[byte]string{OpSub: "'-'", OpMul: "'*'", OpDiv: "'/'", OpMod: "'%'"}[op]
		w("{ Value r = bur_arith(bur_peek(1), bur_peek(0), %s); bur_cur->top -= 2; bur_push(r); }", ch)
		return ip + 1
	case OpNeg:
		w("{ Value v = bur_pop(); bur_push(bur_neg(v)); }")
		return ip + 1
	case OpNot:
		w("{ Value v = bur_pop(); bur_push(bur_not(v)); }")
		return ip + 1
	case OpJump:
		w("goto L%d;", ip+3+u16(0))
		return ip + 3
	case OpJumpIfFalse:
		w("{ Value c = bur_peek(0); if (c.t != VBOOL) bur_trap(\"condition must be a bool, got %%s\", bur_typename(c)); if (!c.u.b) goto L%d; }", ip+3+u16(0))
		return ip + 3
	case OpJumpIfTrue:
		w("{ Value c = bur_peek(0); if (c.t != VBOOL) bur_trap(\"condition must be a bool, got %%s\", bur_typename(c)); if (c.u.b) goto L%d; }", ip+3+u16(0))
		return ip + 3
	case OpJumpIfFalsePop:
		w("{ Value c = bur_peek(0); if (c.t != VBOOL) bur_trap(\"condition must be a bool, got %%s\", bur_typename(c)); bool t = c.u.b; bur_pop(); if (!t) goto L%d; }", ip+3+u16(0))
		return ip + 3
	case OpLoop:
		w("goto L%d;", ip+3-u16(0))
		return ip + 3
	case OpCall:
		w("bur_call(%d);", code[ip+1])
		return ip + 2
	case OpClosure:
		return g.emitClosure(id, code, ip)
	case OpReturn:
		w("{ Value r = bur_pop(); bur_close_upvalues(base); bur_cur->top = base; bur_push(r); return; }")
		return ip + 1
	case OpList:
		n := u16(0)
		w("{ OList *l = bur_new_list(&bur_cur->stack[bur_cur->top - %d], %d); bur_cur->top -= %d; bur_push(bur_obj((Obj *)l)); }", n, n, n)
		return ip + 3
	case OpIndexGet:
		w("{ Value r = bur_index_get(bur_peek(1), bur_peek(0)); bur_cur->top -= 2; bur_push(r); }")
		return ip + 1
	case OpIndexSet:
		w("{ Value val = bur_pop(); Value idx = bur_pop(); Value tgt = bur_pop(); bur_index_set(tgt, idx, val); }")
		return ip + 1
	case OpLen:
		w("{ Value v = bur_pop(); bur_push(bur_int(bur_len(v))); }")
		return ip + 1
	case OpTestVariant:
		w("{ Value et = bur_pop(); Value cand = bur_pop(); bool m = false; if (cand.t == VOBJ && cand.u.o->type == OBJ_ENUMINST) { OEnumInst *in = (OEnumInst *)cand.u.o; m = in->enm == (OEnumType *)et.u.o && in->variant == %d; } bur_push(bur_bool(m)); }", code[ip+1])
		return ip + 2
	case OpGetField:
		w("{ Value v = bur_pop(); OEnumInst *in = (OEnumInst *)v.u.o; bur_push(in->fields[%d]); }", code[ip+1])
		return ip + 2
	case OpNoMatch:
		w("{ Buf nb = {0}; bur_format(&nb, bur_peek(0), true); buf_char(&nb, 0); bur_trap(\"no pattern matched value %%s\", nb.data ? nb.data : \"\"); }")
		return ip + 1
	case OpTry:
		g.emitTry()
		return ip + 1
	case OpSpawn, OpSend, OpRecv, OpChanNext, OpSelect:
		g.fail(fmt.Errorf("C backend: concurrency is not supported yet (opcode %d); use `bur run`", op))
		return len(code)
	default:
		g.fail(fmt.Errorf("C backend: unknown opcode %d", op))
		return len(code)
	}
}

func (g *cgen) emitTry() {
	g.b.WriteString("\t{ Value v = bur_peek(0);\n")
	g.b.WriteString("\t  OEnumInst *in = (v.t == VOBJ && v.u.o->type == OBJ_ENUMINST) ? (OEnumInst *)v.u.o : NULL;\n")
	g.b.WriteString("\t  if (!in || (in->enm != bur_opt_enum && in->enm != bur_res_enum)) bur_trap(\"'?' needs an Option or Result, got %s\", bur_typename(v));\n")
	g.b.WriteString("\t  if (in->variant == 0) { Value inner = in->fields[0]; bur_pop(); bur_push(inner); }\n")
	g.b.WriteString("\t  else { bur_pop(); bur_close_upvalues(base); bur_cur->top = base; bur_push(v); return; } }\n")
}

// emitClosure walks the OpClosure operands (fn const + per-upvalue capture
// descriptors) and emits the closure construction.
func (g *cgen) emitClosure(id int, code []byte, ip int) int {
	fnConst := int(readU16(code, ip+1))
	fn := g.fnConst(id, fnConst)
	p := ip + 3
	fmt.Fprintf(&g.b, "\t{ OClosure *cl = bur_new_closure((OFunc *)bur_consts_%d[%d].u.o); bur_push(bur_obj((Obj *)cl));\n", id, fnConst)
	for i := 0; i < fn.NumUpvals; i++ {
		isLocal := code[p] == 1
		p++
		uidx := int(readU16(code, p))
		p += 2
		if isLocal {
			fmt.Fprintf(&g.b, "\t  cl->upvals[%d] = bur_capture_upvalue(base + %d);\n", i, uidx)
		} else {
			fmt.Fprintf(&g.b, "\t  cl->upvals[%d] = self->upvals[%d];\n", i, uidx)
		}
	}
	g.b.WriteString("\t}\n")
	return p
}

// fnConst returns the OFunc referenced by a function's constant slot.
func (g *cgen) fnConst(id, idx int) *OFunc {
	fn := g.objs[id].(*OFunc)
	return fn.Chunk.Consts[idx].O.(*OFunc)
}

// constStr returns the string held in a function's constant slot (used by
// the global-access opcodes, whose operand names a global).
func (g *cgen) constStr(id, idx int) string {
	fn := g.objs[id].(*OFunc)
	return fn.Chunk.Consts[idx].O.(*OString).S
}

// ---- C literal helpers ------------------------------------------------

// cStr renders s as a C string literal, octal-escaping anything unsafe so an
// escape never absorbs a following digit.
func cStr(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c == '"':
			b.WriteString("\\\"")
		case c == '\\':
			b.WriteString("\\\\")
		case c >= 0x20 && c < 0x7f:
			b.WriteByte(c)
		default:
			fmt.Fprintf(&b, "\\%03o", c)
		}
	}
	b.WriteByte('"')
	return b.String()
}

// cBytes is cStr under a different name, used where the accompanying length
// makes the string's role as a raw byte buffer explicit.
func cBytes(s string) string { return cStr(s) }

// cFloat renders f as an exact C double literal (hex float preserves bits).
func cFloat(f float64) string {
	switch {
	case math.IsInf(f, 1):
		return "INFINITY"
	case math.IsInf(f, -1):
		return "-INFINITY"
	case math.IsNaN(f):
		return "NAN"
	}
	return strconv.FormatFloat(f, 'x', -1, 64)
}
