#ifndef BURRT_NATIVES_H
#define BURRT_NATIVES_H
typedef enum { BUR_NET_LISTENER, BUR_NET_CONN } BurNetKind;
typedef struct {
    int fd;
    BurNetKind kind;
    bool used;
} BurNet;

// cross-unit declarations for the native functions (definitions live in
// burrt_natives.c)
extern bool nat_as_str(Value v, const char **s, int64_t *n) ;
extern OList *nat_as_list(Value v) ;
extern OMap *nat_as_map(Value v) ;
extern void nat_write_joined(Value *args, int argc) ;
extern Value nat_print(Value *args, int argc) ;
extern Value nat_println(Value *args, int argc) ;
extern Value nat_eprintln(Value *args, int argc) ;
extern Value nat_len(Value *args, int argc) ;
extern Value nat_map(Value *args, int argc) ;
extern Value nat_get(Value *args, int argc) ;
extern Value nat_put(Value *args, int argc) ;
extern Value nat_delete(Value *args, int argc) ;
extern Value nat_keys(Value *args, int argc) ;
extern Value nat_push(Value *args, int argc) ;
extern Value nat_pop(Value *args, int argc) ;
extern Value nat_range(Value *args, int argc) ;
extern Value nat_slice(Value *args, int argc) ;
extern Value nat_concat(Value *args, int argc) ;
extern Value nat_contains(Value *args, int argc) ;
extern Value nat_str(Value *args, int argc) ;
extern Value nat_trunc(Value *args, int argc) ;
extern Value nat_to_float(Value *args, int argc) ;
extern Value nat_float_bits(Value *args, int argc) ;
extern Value nat_parse_int(Value *args, int argc) ;
extern Value nat_parse_float(Value *args, int argc) ;
extern Value nat_str_len(Value *args, int argc) ;
extern Value nat_char_at(Value *args, int argc) ;
extern Value nat_byte_at(Value *args, int argc) ;
extern Value nat_split(Value *args, int argc) ;
extern Value nat_join(Value *args, int argc) ;
extern Value nat_substr(Value *args, int argc) ;
extern Value nat_str_contains(Value *args, int argc) ;
extern Value nat_str_index_of(Value *args, int argc) ;
extern Value nat_trim(Value *args, int argc) ;
extern Value nat_chr(Value *args, int argc) ;
extern Value nat_byte_chr(Value *args, int argc) ;
extern Value nat_ord(Value *args, int argc) ;
extern Value nat_read_file(Value *args, int argc) ;
extern Value nat_write_file(Value *args, int argc) ;
extern Value nat_file_exists(Value *args, int argc) ;
extern int nat_strcmp_qsort(const void *a, const void *b) ;
extern Value nat_read_dir(Value *args, int argc) ;
extern Value nat_output(int code, const char *out, int64_t outn, const char *err, int64_t errn) ;
extern int64_t bur_proc_alloc(void) ;
extern void bur_proc_finish(BurProc *p) ;
extern Value bur_proc_result(BurProc *p) ;
extern int64_t bur_proc_spawn(Value cmdv, Value argsv, const char **errmsg) ;
extern Value nat_exec(Value *args, int argc) ;
extern Value nat_exec_start(Value *args, int argc) ;
extern Value nat_exec_poll(Value *args, int argc) ;
extern BurNet *bur_nets;
extern int64_t bur_nnets, bur_netscap;
extern Value bur_net_err(const char *op, const char *msg) ;
extern Value bur_net_ok_str(const char *data, int64_t len) ;
extern int bur_net_socket(int family, int socktype, int protocol) ;
extern int64_t bur_net_alloc(int fd, BurNetKind kind) ;
extern BurNet *bur_net_get(int64_t h, BurNetKind kind) ;
extern void bur_net_cancel_waiters(int fd) ;
extern Value nat_tcp_listen(Value *args, int argc) ;
extern Value nat_tcp_accept(Value *args, int argc) ;
extern Value nat_tcp_dial(Value *args, int argc) ;
extern Value nat_net_read(Value *args, int argc) ;
extern Value nat_net_write(Value *args, int argc) ;
extern Value nat_net_close(Value *args, int argc) ;
extern Value nat_net_nb(Value *args, int argc) ;
extern Value nat_args(Value *args, int argc) ;
extern Value nat_exit(Value *args, int argc) ;
extern Value nat_clock(Value *args, int argc) ;
extern Value nat_type_of(Value *args, int argc) ;
extern Value nat_assert(Value *args, int argc) ;
extern Value nat_chan(Value *args, int argc) ;
extern Value nat_close(Value *args, int argc) ;
extern Value nat_recv(Value *args, int argc) ;
extern Value nat_yield(Value *args, int argc) ;
extern Value nat_sleep(Value *args, int argc) ;
extern void bur_stdin_nonblock(void) ;
extern Value nat_read_stdin(Value *args, int argc) ;
extern Value nat_stdin_nb(Value *args, int argc) ;
extern Value nat_gc(Value *args, int argc) ;
extern Value nat_heap_objects(Value *args, int argc) ;
extern Value nat_gc_cycles(Value *args, int argc) ;
extern void bur_register_native(const char *name, int arity, NativeFn fn) ;
extern void bur_register_natives(void) ;

#endif // BURRT_NATIVES_H
